version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - '8080:3000'
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: root
      POSTGRES_DB: pegueleve_db
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
